### ISSUE TITLE
correct constructDormandLockyerMcCorriganPrince6

### ISSUE THREAD

**Issue by emca1** [SciML/DiffEqDevTools.jl#68]
The output 

https://github.com/SciML/DiffEqDevTools.jl/blob/8fd48e41853575012f39c5146c45c311988f1ac1/src/ode_tableaus.jl#L2384

should be
return(ExplicitRKTableau(A,c,α,6,adaptiveorder=5,αEEst=αEEst,fsal=true))

**Comment by ChrisRackauckas** [comment]
Yes, I think you're correct. Could we get a PR on that?
